site_name: Formula Student Driverless Simulator
theme: readthedocs
site_description: A virtual world where Autonomous Systems from different Formula Student teams can compete in time-trial challenges
repo_name: FS-Driverless/Formula-Student-Driverless-Simulator
repo_url: https://github.com/FS-Driverless/Formula-Student-Driverless-Simulator
edit_uri: 
copyright: GPLv2

nav:
  - "Home": "README.md"
  - "Introduction":
    - "System overview": "system-overview.md"
    - "Getting started": "getting-started.md"
  - "Vehicle & Sensors":
    - "Vehicle model": "vehicle_model.md"
    - "IMU": "imu.md"
    - "Lidar": "lidar.md"
    - "Camera": "camera.md"
    - "GPS": "gps.md"
    - "GSS": "ground-speed-sensor.md"
  - "#tech-madness":
    - "ROS Bridge": "ros-bridge.md"
    - "ROS Bridge statistics": "statistics.md"
    - "Joystick": "joystick.md"
    - "Import your 3d car model": "import-car-3d-model.md"
    - "Google cloud remote workstation": "gcp-remote-workstation.md" 
    - "Software install instructions": "software-install-instructions.md"
    - "How to release": "how-to-release.md"
  - "Competition tooling":
    - "Operator": "operator.md"
    - "System flow and signals": "competition-signals.md"
    - "Spectator": "spectator.md"

extra_css:
  - css\version-select.css
extra_javascript:
  - js\version-select.js
